- name: variables
  hosts: localhost
  vars:
    course: "Devops"
    trainer: "Sivakumar"
    Mode: "Online"
  tasks: #declaring variables task level
    - name: print the information
      vars:
        course: "Terraform"
        trainer: "Ram"
        Mode: "Direct"
        ansible.builtin.debug:
        msg: "I am learning {{course}} from {{trainer}} through {{Mode}}"
    - name: print the information
      ansible.builtin.debug:
        msg: "I am learning {{course}} from {{trainer}} through {{Mode}}"